// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tastekin/TastekinAtlasPreview.tsx": () => import("../components/mockups/tastekin/TastekinAtlasPreview.tsx"),
  "./components/mockups/tastekin/TastekinPreview.tsx": () => import("../components/mockups/tastekin/TastekinPreview.tsx"),
  "./components/mockups/tastekin/TastekinSignalPreview.tsx": () => import("../components/mockups/tastekin/TastekinSignalPreview.tsx")
};
